clear 
[DataIn, fs] = audioread('D:\UNIVERSITY\6th Semester\SS Lab\MyProject\group_talking.wav');

DataOut1 = filter(BandstopFilter500to3000Hz, DataIn);

DataOut2 = filter(LowPass5000Hz, DataOut1);

%sound(DataOut2, fs);

audiowrite('D:\UNIVERSITY\6th Semester\SS Lab\MyProject\group_talking_filtered.wav', DataOut2, fs);

function Hd = BandstopFilter500to3000Hz
%BANDSTOPFILTER500TO3000HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 25-Apr-2025 21:18:16

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N   = 100;   % Order
Fc1 = 500;   % First Cutoff Frequency
Fc2 = 3000;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');
end
% [EOF]

function Hd = LowPass5000Hz
%LOWPASS5000HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 25-Apr-2025 21:27:07

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N  = 50;    % Order
Fc = 5000;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
end
% [EOF]
